FROM		alpine:3.13.4

RUN			apk update && apk upgrade && apk add	\
											yarn	\
											git		\
											openssh

RUN			yarn global add @nestjs/cli ts-node

WORKDIR		/usr/app

COPY		. .

RUN			yarn install

RUN			cp -r ./partylens-permissions ./node_modules

ENTRYPOINT	[ "yarn", "start" ]
